### ISSUE TITLE
Студия не видит нужных библиотек при запуске Demo

### ISSUE THREAD

**Issue by RobertCall** [cvlabmiet/openvxtest#3]
При сборке демо-проекта студия не видит заголовочного файла opencv2/opencv.hpp, хотя при выполнении предыдущих пунктов предварительной настройки никаких ошибок/предупреждений не было. С чем может быть связана проблема?

**Comment by igsha** [comment]
ох, пропустил сообщение. Прошу прощения за задержку с ответом. Разбираюсь. В течение часа-двух отпишусь. А какая конфигурация используется? Visual Studio 2019 Community и vcpkg?

**Comment by RobertCall** [comment]
Да

**Comment by igsha** [comment]
А `opencv3` поставился в систему без ошибок? Проверить можно из директории `vcpkg/installed/x64-windows/include` - есть ли там директории, начинающиеся с `opencv`?
У меня пока не получается самому поставить `opencv3` - какая-то есть проблема с версиями пакетов в vcpkg. Завтра продолжу.

**Comment by RobertCall** [comment]
Да, я искал нужные заголовочные файлы, и проводник находил их в этой директории

**Comment by igsha** [comment]
При генерировании `cmake cache` такие строчки появляются?

![image](https://user-images.githubusercontent.com/5345170/69897297-3a57b680-135b-11ea-8fa7-69fec7e4cd34.png)

Если нет, то в `vcpkg` нужно провести интеграцию с VisualStudio: в powershell прописать `.\vpkgs integrate install`.
Ещё может помочь удалить все проектный файлы *.sln, *.vcxproj.
При дебаггинге самого икзешника необходимо будет пометь путь до изображений (в файле `Demo/Kernels/demo_Threshold.cpp`, например). Так как VS запускает сами исполняемые файлы не из директории `out`, а из `out/build/x64-Debug/Demo`, то пути надо продлить: вместо `"../Image/Solvay_conference_1927.png"` надо написать `"../../../../Image/Solvay_conference_1927.png"`

**Comment by igsha** [comment]
Ещё можете попробовать удалить папку `vcpkg` и проделать операцию установки/интегрирования заново. Не забывайте чистить кеш (вызвать контекстное меню на файле `CMakeLists.txt`, выбрать `Clean cache`) - это тоже иногда помогает.

**Comment by RobertCall** [comment]
Спасибо, всё заработало!
