### ISSUE TITLE
Какой должна быть сигнатура функции?

### ISSUE THREAD

**Issue by RobertCall** [cvlabmiet/openvxtest#4]

**Comment by igsha** [comment]
Это зависит от реализуемого алгоритма. Например, для пороговой обработки сигнатура такая:
```cpp
vx_status ref_Threshold(const vx_image src_image, vx_image dst_image, const vx_threshold thresh);
```
Здесь есть входное изображение `src_image`, выходное изображение `dst_image` и дополнительные параметры `thresh` (это ядро уже сделано, его можно посмотреть в https://github.com/cvlabmiet/openvxtest/blob/master/Lib/Kernels/ref/ref_Threshold.c). Эти параметры потом будут передаваться в ядро уже из https://github.com/cvlabmiet/openvxtest/blob/master/Demo/Kernels/demo_Threshold.cpp, который для своего ядра также нужно написать.

Чтобы понять сигнатуру своего ядра, можно обратиться к [документации](https://drive.google.com/file/d/0B-3W-pT_6OLcRDJoUmZqalBHWVk/view).

**Comment by RobertCall** [comment]
При с проблемой при создании файла .cpp. Я пытаюсь реализовать алгоритм Connected Components Labeling. Если я правильно понял из документации, для вызова этой функции на opencv, необходимо прописать следующие строчки кода:
```
int count_of_labels_cv = -1;
cv::Mat cvImage;
count_of_labels_cv = cv::connectedComponents(m_srcImage, cvImage, 4, CV_32S, cv::CCL_WU);
cv::imshow(m_openCVWindow, cvImage);
```
Но в таком случае результирующее изображение будет абсолютно чёрным, что делает проблематичным проверку моего кода на правильность.

**Comment by igsha** [comment]
Изображение `m_srcImage` должно быть булевым, то есть в нём должно быть только черный и белый цвет. Иначе алгоритм принудительно приводит изображение к булевому с помощью операции `x != 0`, что делает из Вашего изображение тождественным единице.
Для проверки Вам нужно выводить число `count_of_labels_cv` - оно должно быть больше 2 (в идеале около 1000). Воспользуйтесь сначала пороговой функцией, например. Или положите булево изображение в репозиторий.
