### ISSUE TITLE
Ошибка при попытке запуска демо версии (предварительная настройка)

### ISSUE THREAD

**Issue by Leeoree** [cvlabmiet/openvxtest#6]
При запуске demo.exe выводит следующее:

Demo Application contains 1 demos:
0) Threshold
Execute Threshold...
OpenCV(3.4.13) Error: Assertion failed (size.width>0 && size.height>0) in cv::imshow, file E:\Institute\vcpkg\buildtrees\opencv3\src\3.4.13-1d83403e4f.clean\modules\highgui\src\window.cpp, line 382
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(3.4.13) Error: Assertion failed (size.width>0 && size.height>0) in cv::imshow, file E:\Institute\vcpkg\buildtrees\opencv3\src\3.4.13-1d83403e4f.clean\modules\highgui\src\window.cpp, line 382

Моё предположение - неправильно прописанные пути до картинок (меня demo.exe расположен в ..\openvxtest\out\build\x64-Debug (default)\Demo, а не в ..\openvxtest\Realese)

**Comment by igsha** [comment]
Вы использовали `CMakeLists.txt` для конфигурации проекта?

Проверил у себя сейчас - работает. Видимо дейстивтельно проблема именно в запуске. А точнее в директории, из которой запускаете приложение. Можете поэкспериментировать запускать приложение из папки `out`: `out\build\x64-Debug (default)\Demo.exe`. Либо пытаться добиться запуска, меняя путь https://github.com/cvlabmiet/openvxtest/blob/master/Demo/Kernels/demo_Threshold.cpp#L65.

**Comment by Leeoree** [comment]
Да, всё работает если перенести всё содержимое папки ..\openvxtest\out\build\x64-Debug (default)\Demo в ..\openvxtest\out
