### ISSUE TITLE
С чем может быть связан Segmentation fault?

### ISSUE THREAD

**Issue by murenkov** [cvlabmiet/openvxtest#8]
Добрый день.

Натолкнулся на проблему, которую не могу преодолеть. Программа выдаёт ошибку `zsh: segmentation fault (core dumped)  ./demo/demo`.

Как я выяснил, это происходит сразу же при вызове функции `ref_cclabeling()` в файле `demo_cclabeling.cpp`. Из-за этого не могу двигаться дальше.

Текущая версия реализации находится по адресу https://github.com/murenkov/openvxtest.

**Comment by igsha** [comment]
Добрый день.

Вам нужно собрать программу под дебагом. Для это при конфигурации cmake нужно передать флаг `-DCMAKE_BUILD_TYPE=Debug`. Далее собрать программу привычным способом. Запускать программу следует под `gdb`. В этом случае лучше, чтобы программа ничего не спрашивала через стандартный поток ввода.
Когда запустите программу в gdb и она упадёт, gdb покажет строчку кода, где упала. Вы можете воспользоваться командой `bt` для вывода стектрейса. Для **вывода значений переменных** поможет команда `print` (скорее всего где-то присутствует разыменование нулевого указателя). Перемещаться по стеку вызовов можно командами `up`, `down` или задать конкретный стек фрейм через команду `fr`.

Можете поизуть туториалы по использованию gdb: https://www.youtube.com/watch?v=Dq8l1_-QgAc
